supi: 'imsi-001011234567892'
mcc: '001'
mnc: '01'

key: '00000000000000000000000000000000'
op: '00000000000000000000000000000000'
opType: 'OP'
amf: '8000'
imei: '356938035643803'
imeiSv: '4370816125816151'

gnbSearchList:
  - gnb.ueransim.org

uacAic:
  mps: false
  mcs: false

uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

sessions:
  - type: 'IPv4'
    apn: 'internet'
    slice:
      sst: 1
      sd: 1

configured-nssai:
  - sst: 1
    sd: 1

default-nssai:
  - sst: 1
    sd: 1

# Configuraci√≥n "Full": Soportamos todo
integrity:
  IA1: true
  IA2: true
  IA3: true
  IA0: true

ciphering:
  EA1: true
  EA2: true
  EA3: true
  EA0: true

integrityMaxRate:
  uplink: 'full'
  downlink: 'full'